#!/bin/bash                                                                     

# xrandr --output HDMI-0 --mode "1920x1080" --refresh 120
nvidia-settings --assign CurrentMetaMode="HDMI-0: 1920x1080_120 +0+0 {AllowGSYNCCompatible=On}"
