#!/bin/bash                                                                     

# xrandr --output HDMI-0 --mode "1920x1080" --refresh 60
nvidia-settings --assign CurrentMetaMode="HDMI-0: 1920x1080_60 +0+0 {AllowGSYNCCompatible=Off}"
