#!/bin/bash                                                                     

# xrandr --output HDMI-0 --mode "2560x1440" --refresh 120
nvidia-settings --assign CurrentMetaMode="HDMI-0: 2560x1440_120 +0+0 {AllowGSYNCCompatible=On}"
