#!/bin/bash

echo "Current policy:"
for i in {0..7}; do
echo -n "    CPU${i}: "
cpufreq-info -p -c $i
done
echo " "
echo "Current speeds:"
for i in {0..7}; do
echo -n "    CPU${i}: "
cpufreq-info -f -c $i
done
echo " "
