#!/bin/sh

if [ `whoami` != "root" ]; then
   echo "Run this as root"
else
	echo "Switching to ondemand governor"
	echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo ondemand > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
fi
