#!/bin/sh

echo "Current governors:"
echo -n "    CPU0: "
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo -n "    CPU1: "
cat /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
echo " "
echo "Current speeds:"
echo -n "    CPU0: "
cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq 
echo -n "    CPU1: "
cat /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_cur_freq 
echo " "

