#!/usr/bin/perl

# Run a series of doom-ish games with doomsday

use strict;
use warnings;
use diagnostics;

my $home = $ENV{HOME};
my $prefix = "${home}/dosbox/games";

my $iwad = "${prefix}/doom/doom.wad";
my $options = "";
my $brutal = "";

if ($0 =~ /doom2$/) {
    $iwad = "${prefix}/doom2/doom2.wad";
}
elsif ($0 =~ /hexen$/) {
    $iwad = "${prefix}/hexen/hexen.wad";
}
elsif ($0 =~ /heretic$/) {
    $iwad = "${prefix}/heretic/heretic1.wad";
}

if ($0 =~ /brutal/) {
    $brutal = "-file ${prefix}/doom/wads/DoomMetalVol4.wad " . 
      "-file ${prefix}/doom/wads/brutal19.pk3"
}

`gzdoom ${options} -iwad ${iwad} ${brutal}`;
