#!/bin/bash

# This assumes 2 NVMe drives as boot drives. The first drive is
# nvme0n1 and the second drive is nvme1n1. All have 4 partitions, with
# the EFI partition being partition 4. The idea is that, if we sync
# the EFI information to the second drive, it has all the information
# it needs to boot as a degraded array. Switch out the first drive,
# mirror the partition scheme, add the device to the RAID array, let
# it rebuild, and everything will be fine.

EFI_DIR="/boot/efi"
DRIVE="/dev/nvme1n1p4"

TMP_DIR=`mktemp -d /tmp/efi_mount.XXXX`

mount ${DRIVE} ${TMP_DIR} && \
    rsync -a --delete ${EFI_DIR}/ ${TMP_DIR} && \
    umount ${TMP_DIR} && \
    rmdir ${TMP_DIR}

