#!/bin/bash

export PROTON_LOG=0
export MANGOHUD=0
export WINE_FULLSCREEN_FSR=1
export WINE_FULLSCREEN_FSR_STRENGTH=0
export DXVK_ASYNC=1
# export RADV_PERFTEST=rt

xfconf-query -c xfce4-notifyd -p /do-not-disturb -s true
eval "gamemoderun $@"
xfconf-query -c xfce4-notifyd -p /do-not-disturb -s false
