#!/bin/bash

URL=https://owncloud.mattcaron.net/remote.php/webdav

echo -n "Enter password: "
read -s pw
echo ""
CREDENTIALS="$HOME/.davfs2/secrets"
echo "$URL $USER \"$pw\"" >> $CREDENTIALS
chmod 600 $CREDENTIALS

# This needs to be root, otherwise mount.davfs complains, since we're
# running as root.
echo $pw | sudo -S chown root $CREDENTIALS

echo $pw | sudo -S mount -t davfs -o \
    conf=$HOME/.davfs2/davfs2.conf,uid=$USER,gid=$USER \
    https://owncloud.mattcaron.net/remote.php/webdav \
    $HOME/owncloud

echo $pw | sudo -S rm $CREDENTIALS
