#!/usr/bin/perl -w
use strict;
use warnings;

# Set to the directory you want to have searched for photos
my $searchPath = '/home/matt/workspace/pics/xfce_wallpaper /home/matt/workspace/pics/photos/family/kids/general';
# Edit to the number of seconds between photo switches
my $switchTime = 600;

my @photos = `find $searchPath -type f | grep [jJ][pP][eE]*[gG]`;
chomp(@photos);
my $photo;

my $running = `ps -ef | grep random_wallpaper | grep perl | grep -v grep | wc -l`;

chomp($running);

# print "Running = $running\n";

# Race condition - wait for the desktop manager/window
# manager/whatever to start and be happy.
sleep(5); 

# We will always get ourselves in the above count
if ($running eq "1") {
    while(1)
    {
        $photo = $photos[rand($#photos)];
        print "Photo is ${photo}\n";
        # Mate
        # `mateconftool-2 --type string --set /desktop/mate/background/picture_filename "$photo"`;

        # Gnome
        # `gconftool-2 --type string --set /desktop/gnome/background/picture_filename "$photo"`;

        # general
        # `xli -onroot -fullscreen "$photo"`;
        
        # old Xfce
        #`echo "# xfce backdrop list\n$photo" > ~/.config/xfce4/desktop/backdrop.list && xfdesktop --reload`;
    
        # newer Xfce
        # `echo "# xfce backdrop list\n$photo" > ~/.config/xfce4/desktop/backdrop.list && xfdesktop --reload`;
        
        # lxde
        # `pcmanfm -w ${photo}`;

        # New Mate (Ubuntu Mate 20.04)
        `dconf write /org/mate/desktop/background/picture-filename "'$photo'"`;

        sleep($switchTime);
    }
}
else {
    print "Already running, exiting\n"
}

