#!/bin/bash                                                                     

xrandr --output HDMI-A-0 --mode "3840x2160" --refresh 30 --set TearFree on
xrandr --auto
xrandr --query
echo
echo press enter to continue
echo
read

