#!/bin/bash

HOST=`hostname`

if [ $HOST == "hiro" ]; then
    xrandr --output eDP-1 --mode "1920x1080" --refresh 60
    xrandr --output HDMI-1-0 --mode "3840x2160" --refresh 30
elif [ $HOST == "bluebox" ]; then
    # 60fps looks better for plain text; no need for VRR in this case.
    nvidia-settings --assign CurrentMetaMode="HDMI-0: 3840x2160_60 +0+0 {AllowGSYNCCompatible=Off}"
else
    echo "Unknown host ${HOST}, not doing anything special."
fi

if [ "$1" != "--quiet" ]; then
    xrandr --auto
    xrandr --query
    echo
    echo press enter to continue
    echo
    read
fi
