#!/bin/bash

wget -np -m -e robots=off -U "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36" -w 2 --random-wait https://file.wikileaks.org/file/
