#!/usr/bin/perl -w
use strict;
use warnings;

# Edit to the number of seconds between photo switches
my $switchTime = 600;

my @photos = `find $searchPath -type f | grep [jJ][pP][eE]*[gG]`;
chomp(@photos);
my $photo;

my $running = `ps -ef | grep xfdesktop_hup | grep perl | grep -v grep | wc -l`;

chomp($running);

# Race condition - wait for the desktop manager/window
# manager/whatever to start and be happy.
sleep(5); 

# We will always get ourselves in the above count
if ($running eq "1") {
    while(1) {
        `xfdesktop --reload`;
        sleep($switchTime);
    }
}
else {
    print "Already running, exiting\n"
}

